// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//! # Keystone API types Error
use thiserror::Error;

#[cfg(feature = "builder")]
pub use openstack_keystone_core_types::error::BuilderError;

/// Keystone API operation errors.
#[derive(Debug, Error)]
pub enum KeystoneApiError {
    /// Selected authentication is forbidden.
    #[error("changing current authentication scope is forbidden")]
    AuthenticationRescopeForbidden,

    #[error("Attempted to authenticate with an unsupported method.")]
    AuthMethodNotSupported,

    #[error("{0}.")]
    BadRequest(String),

    /// Base64 decoding error.
    #[error(transparent)]
    Base64Decode(#[from] base64::DecodeError),

    #[error("conflict, resource already existing")]
    Conflict(String),

    #[error("domain id or name must be present")]
    DomainIdOrName,

    #[error("You are not authorized to perform the requested action.")]
    Forbidden {
        /// The source of the error.
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },

    #[error("invalid header header")]
    InvalidHeader,

    #[error("invalid token")]
    InvalidToken,

    #[error("internal server error: {0}")]
    InternalError(String),

    #[error("could not find {resource}: {identifier}")]
    NotFound {
        resource: String,
        identifier: String,
    },

    /// Others.
    #[error(transparent)]
    Other(#[from] eyre::Report),

    #[error("project id or name must be present")]
    ProjectIdOrName,

    #[error("project domain must be present")]
    ProjectDomain,

    /// Selected authentication is forbidden.
    #[error("selected authentication is forbidden")]
    SelectedAuthenticationForbidden,

    /// (de)serialization error.
    #[error(transparent)]
    Serde {
        #[from]
        source: serde_json::Error,
    },

    #[error("missing x-subject-token header")]
    SubjectTokenMissing,

    #[error("The request you have made requires authentication.")]
    UnauthorizedNoContext,

    #[error("{}", .context.clone().unwrap_or("The request you have made requires authentication.".to_string()))]
    Unauthorized {
        context: Option<String>,
        /// The source of the error.
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
}

impl KeystoneApiError {
    pub fn forbidden<E>(error: E) -> Self
    where
        E: std::error::Error + Send + Sync + 'static,
    {
        Self::Forbidden {
            source: Box::new(error),
        }
    }

    pub fn internal<E>(error: E) -> Self
    where
        E: std::error::Error + Send + Sync + 'static,
    {
        Self::InternalError(error.to_string())
        //{
        //    source: Box::new(error),
        //}
    }

    pub fn not_found<R, I>(resource: R, identifier: I) -> Self
    where
        R: Into<String>,
        I: Into<String>,
    {
        Self::NotFound {
            resource: resource.into(),
            identifier: identifier.into(),
        }
    }

    pub fn unauthorized<E, C>(error: E, context: Option<C>) -> Self
    where
        E: std::error::Error + Send + Sync + 'static,
        C: Into<String>,
    {
        Self::Unauthorized {
            context: context.map(Into::into),
            source: Box::new(error),
        }
    }
}

///// Builder error.
/////
///// A wrapper error that is used instead of the error generated by the
///// `derive_builder`.
//#[derive(Debug, Error)]
//#[non_exhaustive]
//pub enum BuilderError {
//    /// Uninitialized field.
//    #[error("{0}")]
//    UninitializedField(String),
//    /// Custom validation error.
//    #[error("{0}")]
//    Validation(String),
//}
//
//impl From<String> for BuilderError {
//    fn from(s: String) -> Self {
//        Self::Validation(s)
//    }
//}
//
//impl From<derive_builder::UninitializedFieldError> for BuilderError {
//    fn from(ufe: derive_builder::UninitializedFieldError) -> Self {
//        Self::UninitializedField(ufe.to_string())
//    }
//}
//
//impl From<BuilderError> for KeystoneApiError {
//    fn from(value: BuilderError) -> Self {
//        Self::InternalError(value.to_string())
//    }
//}
